print(1 > 2)  # False
print(1 < 2)  # True
print(1 <= 2)  # True
print(1 >= 2)  # False
print(2 >= 2)  # True
print(2 <= 2)  # True
print(1 == 1)  # True
print(1 == 2)  # False
print(1 == "2")    # False
print(1 != 2)   # True
print(2 != 2)   # False
